create table if not exists tbl_posts_temp
(
    post_id varchar(255) not null primary key,
    doc_type          smallint,
    source_type       smallint,
    crawl_source      smallint,
    crawl_source_code char(4),
    pub_time          bigint,
    crawl_time        bigint,
    subject_id        varchar(255),
    title             varchar(500),
    description       text,
    content           text,
    url               varchar(500) not null,
    media_urls        text,
    comments          int,
    shares            int,
    reactions         int,
    favors            int,
    views             int,
    web_tags          varchar(1000),
    web_keywords      varchar(1000),
    auth_id           varchar(500),
    auth_name         varchar(500),
    auth_type         smallint,
    source_id         varchar(500),
    source_name       varchar(500),
    reply_to          varchar(255),
    level             int,
    org_id            int not null,
    sentiment         integer  default 0,
    is_sent           smallint default 0,
    tag1              varchar(255),
    tag2              varchar(255),
    tag3              varchar(255),
    spam              smallint default 0,
    completed         smallint,
    source_url        varchar(500),
    auth_url          varchar(500),
    bot_id            varchar(31)
);